Set up basic model and app structure for Arrangement
wemadefree/WeBook pull request #1
Opened 2021-10-12 11:16 UTC by magnuhar

### Summary
This PR aims to set up a basic skeleton as far as models and the registering of those models within the inbuilt administration panel for Django go, with the arrangement app/section in mind. 

**Concretely, the following has been done:**
1. Set up a new app by the name of _Arrangement_
2. Removed normal tests.py file generated by Django, we prefer to have this in a folder instead (see _users_ app for reference)
3. Gitignored the .idea folder generated by PyCharm IDE
4. Set up an initial first draft of the models as mapped and envisioned (_which of course is still open to much change)_
5. Registered the models created in admin.py under Arrangement

**I have taken the liberty of assuming the following conventions:**
1. We always want to explicitly specify our table names in our models
2. We want Django ORM to handle our Id attributes/fields
3. We do not want to create our own mapping models in many-to-many relationships, prefering rather to allow Django ORM to handle this complexity for us through the ManyToManyField class. I am not entirely certain as to what is the best choice here, so input would be great. There are definite upsides and downsides whichever way one chooses to go - but with my limited Django experience it is hard to see what ramifications each option may have in the future. Maybe it's a non-issue? 

Also - the main focus of this PR was to establish the relations between the models, and start mocking things up with that in mind. I have not given OnDelete behaviour much thought, nor have I accurately filled out all attributes (should be close though).

2021-10-15 06:22 UTC, eivl requested changes
fiks changes. legg til docstrings, så skal jeg se over den igjen. 
overrasket over hvor mange mange til mange forhold vi har. kan noen av dem kanskje sees på som en Enum? det gir ikke mulighet for kunden å legge til nye, da må vi gjøre det selv, men det er noe å tenke litt på. Jeg syns generelt det er greit å ikke bruke Enums, men de er jo veldig nyttige av og til.

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +    class Meta:
Forklar meg explicitly hvorfor du har lyst til å sette db navnet? 

Django lager DB navnet selv basert på app navn og klassenavn. 
```
For example, if you have an app bookstore (as created by manage.py startapp bookstore), a model defined as class Book will have a database table named bookstore_book.
```
problemet med å navngi tabellene er når du ender opp med klasser fra forskjellige apper med samme navn, da klarer du ikke lett å se forskjell. 

Jeg foreslår at du lar django håndtere db_table navngivningen så fremst du ikke har en god grunn til å forandre det. 

og når du forandrer, så må navnet være lett å se hva det tilhører. Det er nemlig ikke selvforklarerene at `audiences` har noe med vår `arrangement` app å gjøre, mens `arrangement_audience` som er navnet django ville laget selv, virker veldig fornuftig.

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +    class Meta:
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "rooms"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "articles"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "organizationtypes"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "timelineevents"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "servicetypes"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "businesshours"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        return f"{self.start_of_business_hours} - {self.end_of_business_hours}"
det er uklart hva dette kommer til å bli. lag en docstring med eksempler så vi har en klar forståelse om hva dette kommer til å se ut som.

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +    # TODO: Make connection between owner (Person)
ikke push TODO til produksjon. Det er greit å ha TODO i dev branchen, det er derimot ikke greit å ha det i prod.

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "calendars"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "Notes"
samme som første Meta class
og ikke bruk store bokstaver i db tabel navn.

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +    confirmed_when = models.DateTimeField("ConfirmedWhen")
er disse feltene påkrevd når man lager en kvittering?

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "confirmationreceipts"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        return f"{self.requested_by.get_name()} petitioned {self.sent_to} for a confirmation at STAMP."
det er uklart hva dette kommer til å returnere, lag en docstring som forklarer dette.

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "people"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "organizations"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "serviceproviders"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "events"
samme som første Meta class

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +    # TODO: Connect to receipt
ikke bruk TODO i production, er helt greit å bruke det i dev. skal du ha noe i produksjon, så skal koden være skrevet.

2021-10-15 06:22 UTC, eivl commented on webook/arrangement/models.py
> +        db_table = "eventservices"
samme som første Meta class

2021-10-18 05:32 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "rooms"
Fixed

2021-10-18 05:32 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "articles"
Fixed

2021-10-18 05:32 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "organizationtypes"
Fixed

2021-10-18 05:32 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "timelineevents"
Fixed

2021-10-18 05:33 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "servicetypes"
Fixed / removed

2021-10-18 05:33 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "businesshours"
Fixed / removed

2021-10-18 05:34 UTC, magnuhar commented on webook/arrangement/models.py
> +        return f"{self.start_of_business_hours} - {self.end_of_business_hours}"
Lagt til docstrings på alle __str__() metoder, samt alle modell klasser.

2021-10-18 05:34 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "calendars"
Fixed / removed

2021-10-18 05:34 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "Notes"
Fixed / removed

2021-10-18 05:36 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "confirmationreceipts"
Fixed / removed

2021-10-18 05:36 UTC, magnuhar commented on webook/arrangement/models.py
> +        return f"{self.requested_by.get_name()} petitioned {self.sent_to} for a confirmation at STAMP."
Lagt til docstring

2021-10-18 05:36 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "people"
Fixed / removed

2021-10-18 05:37 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "serviceproviders"
Fixed / removed

2021-10-18 05:37 UTC, magnuhar commented on webook/arrangement/models.py
> +        db_table = "events"
Fixed / removed

2021-10-18 05:37 UTC, magnuhar commented on webook/arrangement/models.py
> +    # TODO: Connect to receipt
Resolvet ToDo's

2021-10-18 05:43 UTC, magnuhar commented on webook/arrangement/models.py
> +    class Meta:
Jeg har fjernet all eksplisitt naming av tabeller. 
Lest litt mer om det og det virker som at den aksepterte konvensjonen er å la Django håndtere det.

2021-10-22 06:16 UTC, merged